name: CI
on: [push]
jobs:
  build:
    name: Build and test qunq package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: '1.14'
      - run: go build ./qunq
      - run: go test -cover ./qunq
